#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>
#include "bubbleSort.h"
#include "selectSort.h"
#include "insertSort.h"
#include "mergeSort.h"
#include "helperFunctions.h"