#include <assert.h>
#include "bubbleSort.h"
#include "insertSort.h"
#include "selectSort.h"
#include "mergeSort.h"
#include "heapSort.h"
#include "helperFunctions.h"
#include <stdio.h>
#include <string.h>

void testSwap();
void testMerge();
void testBubbleSort();
void testSelectSort();
void testInsertSort();
void testMergeSort();
void testHeapSort();
void testBuildMaxHeap();
void testMaxHeapify();